#ideal_width = 80
#max_width = 120
reorder_imports = true
reorder_imported_names = true
where_trailing_comma = true
#fn_arg_indent = "Tabbed"
#fn_args_layout = "Block"
#struct_lit_multiline_style = "ForceMulti"
format_strings = false
